[env]
TERM = "xterm-256color"

[window]
opacity = 0.80
decorations = "None"
dynamic_padding = true
startup_mode = "Windowed"

[window.padding]
x = 10
y = 12

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16

[font.normal]
family = "Agave Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Agave Nerd Font Mono"
style = "Regular"

[font.italic]
family = "Agave Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "Agave Nerd Font Mono"
style = "Regular"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750
unfocused_hollow = true

[selection]
save_to_clipboard = true

[bell]
animation = "EaseOutExpo"
duration = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"








































































[colors.primary]
background = '#282a36'
foreground = '#f8f8f2'

[colors.cursor]
text = '#282a36'
cursor = '#ff79c6'

[colors.selection]
text = '#282a36'
background = '#ff79c6'

[colors.normal]
black = '#44475a'
red = '#ff5555'
green = '#50fa7b'
yellow = '#f1fa8c'
blue = '#8be9fd'
magenta = '#ff79c6'
cyan = '#8be9fd'
white = '#f8f8f2'

[colors.bright]
black = '#44475a'
red = '#ff5555'
green = '#50fa7b'
yellow = '#f1fa8c'
blue = '#8be9fd'
magenta = '#ff79c6'
cyan = '#8be9fd'
white = '#6272a4'
