[env]
TERM = "xterm-256color"

[window]
opacity = 0.80
decorations = "None"
dynamic_padding = true
startup_mode = "Windowed"

[window.padding]
x = 8
y = 10

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16
normal = { family = "Agave Nerd Font Mono", style = "Regular" }
bold   = { family = "Agave Nerd Font Mono", style = "Regular" }
italic = { family = "Agave Nerd Font Mono", style = "Regular" }
bold_italic = { family = "Agave Nerd Font Mono", style = "Regular" }

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 600

[selection]
save_to_clipboard = true

[bell]
animation = "EaseOutExpo"
duration = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"














































































































































































































































































































































































































































































































































































































































[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

[colors.cursor]
text = '#1a1b26'
cursor = '#bb9af7'

[colors.selection]
text = '#1a1b26'
background = '#bb9af7'

[colors.normal]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#1abc9c'
white = '#c0caf5'

[colors.bright]
black = '#545c7e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#1abc9c'
white = '#a9b1d6'
