[env]
TERM = "xterm-256color"

[window]
opacity = 0.80
decorations = "None"
dynamic_padding = true
startup_mode = "Windowed"

[window.padding]
x = 8
y = 10

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16
normal = { family = "Agave Nerd Font Mono", style = "Regular" }
bold   = { family = "Agave Nerd Font Mono", style = "Regular" }
italic = { family = "Agave Nerd Font Mono", style = "Regular" }
bold_italic = { family = "Agave Nerd Font Mono", style = "Regular" }

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 600

[selection]
save_to_clipboard = true

[bell]
animation = "EaseOutExpo"
duration = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"


































































































































































































































































































































































































































































































































































































































[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

[colors.cursor]
text = '#282828'
cursor = '#d3869b'

[colors.selection]
text = '#282828'
background = '#d3869b'

[colors.normal]
black = '#504945'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#ebdbb2'

[colors.bright]
black = '#665c54'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#d5c4a1'
