[colors.primary]
background = '#eff1f5'
foreground = '#4c4f69'

[colors.cursor]
text = '#eff1f5'
cursor = '#ea76cb'

[colors.selection]
text = '#eff1f5'
background = '#ea76cb'

[colors.normal]
black = '#bcc0cc'
red = '#d20f39'
green = '#40a02b'
yellow = '#df8e1d'
blue = '#1e66f5'
magenta = '#ea76cb'
cyan = '#179299'
white = '#5c5f77'

[colors.bright]
black = '#acb0be'
red = '#d20f39'
green = '#40a02b'
yellow = '#df8e1d'
blue = '#1e66f5'
magenta = '#ea76cb'
cyan = '#179299'
white = '#6c6f85'
