[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

[colors.cursor]
text = '#282828'
cursor = '#d3869b'

[colors.selection]
text = '#282828'
background = '#d3869b'

[colors.normal]
black = '#504945'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#ebdbb2'

[colors.bright]
black = '#665c54'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#d5c4a1'
