[env]
TERM = "xterm-256color"

[window]
opacity = 0.80
decorations = "None"
dynamic_padding = true
startup_mode = "Windowed"

[window.padding]
x = 8
y = 10

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16
normal = { family = "Agave Nerd Font Mono", style = "Regular" }
bold   = { family = "Agave Nerd Font Mono", style = "Regular" }
italic = { family = "Agave Nerd Font Mono", style = "Regular" }
bold_italic = { family = "Agave Nerd Font Mono", style = "Regular" }

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 600

[selection]
save_to_clipboard = true

[bell]
animation = "EaseOutExpo"
duration = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"










































































































































































































































































































































































































































































































































































































































[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

[colors.cursor]
text = '#1e1e2e'
cursor = '#f5c2e7'

[colors.selection]
text = '#1e1e2e'
background = '#f5c2e7'

[colors.normal]
black = '#45475a'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#f5c2e7'
cyan = '#94e2d5'
white = '#bac2de'

[colors.bright]
black = '#585b70'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#f5c2e7'
cyan = '#94e2d5'
white = '#a6adc8'
