[colors.primary]
background = '#282a36'
foreground = '#f8f8f2'

[colors.cursor]
text = '#282a36'
cursor = '#ff79c6'

[colors.selection]
text = '#282a36'
background = '#ff79c6'

[colors.normal]
black = '#44475a'
red = '#ff5555'
green = '#50fa7b'
yellow = '#f1fa8c'
blue = '#8be9fd'
magenta = '#ff79c6'
cyan = '#8be9fd'
white = '#f8f8f2'

[colors.bright]
black = '#44475a'
red = '#ff5555'
green = '#50fa7b'
yellow = '#f1fa8c'
blue = '#8be9fd'
magenta = '#ff79c6'
cyan = '#8be9fd'
white = '#6272a4'
