[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

[colors.cursor]
text = '#1a1b26'
cursor = '#bb9af7'

[colors.selection]
text = '#1a1b26'
background = '#bb9af7'

[colors.normal]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#1abc9c'
white = '#c0caf5'

[colors.bright]
black = '#545c7e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#1abc9c'
white = '#a9b1d6'
